### PR TITLE
Remove circular dependency

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Any idea how to fix the circleci build fail? It fails with and without the `perl` build requirement.

**Comment by jakirkham** [comment]
Thanks for noting the `perl`issue, @nsoranzo. We will look into it.

However, we can't really accept this submission as we wish to keep the test step. Also, `flex` is required as part of the build too. So this really won't work. I hope you understand.

Please let us know if you have any questions.

**Comment by jakirkham** [comment]
See this PR ( https://github.com/conda-forge/bison-feedstock/pull/3 ) for fixing `perl`.

**Comment by nsoranzo** [comment]
> However, we can't really accept this submission as we wish to keep the test step. Also, `flex` is required as part of the build too. So this really won't work. I hope you understand.

I am pretty sure `flex` is not needed for the build, in fact the build completes fine on my local machine without `flex` and also the OS X build on Travis.

> See this PR ( #3 ) for fixing `perl`.

Thanks!

**Comment by jakirkham** [comment]
I have forgotten the exact details of the build. I know we need it for the tests. I believe it may be used in the build too, but it has been a few months since I dived into these. In any event, dropping the tests to solve this isn't really an option.

So, OS X is a bad test case as it has both of these to start with. The challenging part of configuring these was getting Linux to work as we provide neither. Hence their current configuration.

**Comment by ocefpaf** [comment]
@nsoranzo `flex` and `bison` do have this circular dependencies. You can build one without the other, but some features will be missing. So you need to build one without the other, build the other, re-build the one... That is sadly common practice in many gnu old tools.

**Pull request closed without merging**
