### PR TITLE
WIP: Add Windows builds

### PR DESCRIPTION
**Pull request by certik**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by certik** [comment]
@conda-forge-admin, please rerender

**Comment by mingwandroid** [comment]
Removing flex from bison is not something we should contemplate, simply, things use it and expect it and they will break if it isn't there.

Is `m2-bison` not good enough for your needs here? It does support `flex`.

**Comment by certik** [comment]
Yeah I just noticed that the build fails without flex. What is the purpose of the `m2-*` packages? (Where are they built, I can't find any `m2-bison-feedstock`...)

So far for all other packages, I simply installed exactly the same package name on all 3 platforms (Win, macOS and Linux).

**Comment by mingwandroid** [comment]
`m2` means `msys2`. It is a fork of Cygwin with the explicit goal of smooth interoperation with 'normal' Windows software.

It implements the POSIX standard on top of the native WIN32 API allowing traditional Unix software such to work. Specifically, things such as the FHS and forking are made possible (and well, loads more).

MSYS2 exists to support native Windows software delelopment, really, but it also forms the core of "Git for Windows", though *really* at core all these things are Cygwin-y with a few bits changed and added. The original MSYS was created, more or less, so that `configure && make && make install` would work on Windows *and* generate software (when given appropriate compilers) software that does not depend upon the msys2/Cygwin runtime.

The Anaconda Distro imported enough packages from MSYS2 to allow us to build what we need. This includes flex and bison.

**Comment by certik** [comment]
@mingwandroid thanks. Yes, I am familiar with `msys2`, but not its Conda integration. Are the `m2-*` packages in Anaconda, but not conda-forge?

I'll try `m2-bison`, that might work for me.

Are you opposed to have proper Windows support for conda-forge's Flex and Bison?

**Comment by certik** [comment]
I just tested the `m2-bison` package and it works for me. Thanks for the tip.

I still think the "clean" approach is to make sure this repository's `bison` builds properly on Windows at conda-forge.

**Comment by mingwandroid** [comment]
_Of_ course we'd prefer to build from source here. There's no reason we cannot build from source from the latest msys2 recipe. They are even more pro open source than CF., refusing ever to release binaries built elsewhere. 

The problem is that esp. for gnu software there's little to no interest in supporting closed source compilers. For that reason, if you want flex support in a bison compiled with MSVC then you would have to do a lot of work to make that happen. For me there are more immersing things to do. Far too many of them for me to care enough about this minor wrinkle.

But again a bison without flex is not much use.

**Comment by certik** [comment]
@mingwandroid thanks for the feedback. Can you please clarify the situation with flex in bison: it seems flex is required to build bison from source. That's one issue. But from your comments, it seems that flex is also needed at runtime, in order to use bison with flex? I personally use bison with re2c. But I could just as well switch to flex if I wanted. Either way, bison does not know what tokenizer I use.

So one could, for example, try to build Bison with flex from `m2-flex`. But your comment seems to suggest one has to somehow link against it at runtime (I can see how that becomes more difficult).

**Comment by mingwandroid** [comment]
Bison can and does call flex directly at runtime. Here is a sample file: https://github.com/ecnerwala/flex-bison-2-parser-example/blob/master/parser2.yy

While it's great that your needs are slim here, but that's not the case for a general `bison` package where the expectation is that it is fully featured.

**Comment by certik** [comment]
I must be missing something. The file you posted declares `zzlex` as the lexer function that the generated Bison parser calls. However, Bison itself doesn't seem to know anything about flex, and you have to compile the Flex file by hand, as is done here:

https://github.com/ecnerwala/flex-bison-2-parser-example/blob/10a82028b18ff0d9aebe6cef1355dd106958f1e3/Makefile#L8

So as long as the `flex` executable is provided by the `m2-flex` package, and the `bison` by the `bison` package, things should work.

Unless what you mean that when you install `bison`, it should also install some flex package automatically, even if technically bison does not depend on flex at runtime?

**Comment by mingwandroid** [comment]
If you can build such a bison then I don't mind but it must pass the test suite with me-flex installed for it to be generally useful.

**Comment by certik** [comment]
So everything seems to build on Windows, but there are a lot of test failures. I don't know if the m2-bison package also fails the tests (and they just don't run them), or if m2-bison passes all tests and it's this PR that is buggy.

**Comment by certik** [comment]
The test output is now available in the logs. It's all kinds of different failures, I wonder if it's somehow picking up some older bison that is available on the image (?), rather than the just compiled one.

**Comment by certik** [comment]
I found this repository: https://github.com/lexxmark/winflexbison, where they got Bison to build with MSVC. I don't want to maintain any difficult set of fixes, only if it's relatively simple to get things to build and pass tests on Windows. I am going to keep this PR open for now, and try a few more things.

**Comment by certik** [comment]
So the Windows package builds if we skip tests (there are a lot of failures). I don't know how to fix them unfortunately.

**Comment by jakirkham** [comment]
Would you be able to use [`m2-bison`]( https://anaconda.org/msys2/m2-bison )? That might be easier if you just need this as a command line tool.

**Comment by certik** [comment]
@jakirkham yes, I've been using `m2-bison` and it works great. I just think this `bison` package itself should have Windows builds one way or another, but it would require more work. I am closing this PR, as I don't know how to fix it.

**Pull request closed without merging**
